### ISSUE TITLE
How does one load image not from cl.import_example

### ISSUE THREAD

**Issue by johngrabner** [erdogant/clustimage#21]
Thank you for this cool library.

How does one load images from sources other than your cl.import_example(data='flowers')?

My images are in mySQL database.  If needed, I can put them into a directory.

Also, I'd appreciate recommended setting to group images like the following.  
![image](https://github.com/erdogant/clustimage/assets/8209285/ecd31d77-2d4e-494d-8000-88eb9855cec3)

**Comment by johngrabner** [comment]
The code "def fit_transform" makes it clear
X : [str of list] or [np.array].
            The input can be:
                * "c://temp//" : Path to directory with images
                * ['c://temp//image1.png', 'c://image2.png', ...] : List of exact pathnames.
                * [[.., ..], [.., ..], ...] : np.array matrix in the form of [sampels x features]

So drop part one of my question.

**Comment by erdogant** [comment]
Great! There are also a number of examples at the [documentation pages](https://erdogant.github.io/clustimage/pages/html/Examples.html#module-clustimage.clustimage.url2disk).

In response to your other question; _group images like shown_. That can be quite tricky because the size of the images needs to be the same (or it needs to be scaled). Alternatively, maybe a hash function can help in this case? Have a look at [undouble ](https://github.com/erdogant/undouble)which is a library that I created to undouble images. A more detailed explanation is in this [blog](https://towardsdatascience.com/detection-of-duplicate-images-using-image-hash-functions-4d9c53f04a75).

**Comment by johngrabner** [comment]
Thank you for the response.  I will try both clustimage and undouble.

If the above does not yield adequate results, I will
give an auto-encode a try. Do you have any experience with auto-encoder based image clustering?

The though being that if I input both the image and string, compress to a small embedding, then expands. The
embedding will contain salient information that I could use for clustering.  Never tried this so idea if this is reasonable or not.

Anyhow, thanks for these libraries.

Regards,
John





________________________________
